# Generated by Django 4.1.5 on 2023-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_client_date_alter_client_billing_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="gst_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="pan_number",
            field=models.CharField(max_length=100),
        ),
    ]
