# Generated by Django 4.1.5 on 2023-02-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_client_gst_number_alter_client_pan_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="company_name",
        ),
    ]
