# Generated by Django 4.1.5 on 2023-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_project_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="max_hours",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
