# Generated by Django 4.1.5 on 2023-03-21 09:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_resource_max_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("item_1", models.CharField(max_length=50, null=True)),
                ("item_2", models.CharField(max_length=50, null=True)),
                ("item_3", models.CharField(max_length=50, null=True)),
                ("item_4", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
