# Generated by Django 4.1.5 on 2023-03-29 06:28

from django.db import migrations, models
import django.utils.timezone
from datetime import timedelta


default_duration = timedelta(hours=0)
class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_milestone_project_no_milestone_milestone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="hours",
            field=models.DurationField(default=default_duration),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resource",
            name="max_hours",
            field=models.DurationField(default=default_duration),
            preserve_default=False,
        ),
    ]
